apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./alerts/alert1.yaml
- ./alerts/alert2.yaml

# Configure namespace
namespace: redhat-rhaom-observability

patches:
- path: ./patches/patch.yaml
  target:
    kind: PrometheusRule
