kind: Deployment
apiVersion: apps/v1
metadata:
  name: ratelimit
  namespace: redhat-rhoam-marin3r
spec:
  selector:
    matchLabels:
      app: ratelimit
  template:
    spec:
      containers:
        - name: ratelimit
          image: 'quay.io/3scale/limitador:0.5.1'
