kind: Deployment
apiVersion: apps/v1
metadata:
  name: marin3r-instance
spec:
  template:
    spec:
      containers:
        - args:
          name: marin3r
          image: 'quay.io/3scale/marin3r:v0.11.0'