apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhoam-missing-metrics
spec:
  groups:
    - name: rhoam-general.rules
      rules:
        - alert: RHOAMCriticalMetricsMissing
          annotations:
            message: one or more critical metrics have been missing for 20+ minutes
            sop_url: >-
              https://gitlab.cee.redhat.com/rhcloudservices/integreatly-help/blob/master/sops/rhoam/alerts/CriticalMetricsMissing.asciidoc
          expr: >-
            (absent(kube_endpoint_address_available) or
            absent(kube_pod_container_status_ready) or absent(kube_pod_labels)
            or absent(kube_pod_status_phase) or absent(kube_pod_status_ready) or
            absent(kube_secret_info) or absent(rhoam_version) or
            absent(threescale_portals)) == 1
          for: 20m
          labels:
            severity: critical