apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: alerts-stable
  namespace: openshift-gitops
spec:
  description: project for alerting stable environment
  destinations:
    - name: in-cluster
      namespace: '*'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/MStokluska/testGitOps'